services:
  backend:
    image: OnlineShop/backend
    build:
      context: ./BackEnd/
    ports:
      - "8081:5242"
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      - ConnectionStrings__ViteConnection=${ConnectionStrings__ViteConnection}
      - DB_CONNECTION=${DB_CONNECTION}

  migrator:
    image: OnlineShop/backend
    command: [ "app/efbundle", "--connection", "${DB_CONNECTION}" ]
    depends_on:
      db:
        condition: service_healthy
    restart: no

  frontend:
    image: OnlineShop/frontend
    build:
      context: ./FrontEnd
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -Q \"SELECT 1\" -b -l 5 || exit 1" ]
      interval: 10s
      timeout: 8s
      retries: 6
      start_period: 15s
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:
