name: Check
on: push
jobs:
    dotnet:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: BackEnd
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            - name: Test
              run: dotnet test --no-build --verbosity normal
    vite:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: FrontEnd
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install deps
          uses: npm ci
        - name: Lint
          uses: npm run lint